version: "3.9"
services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_DB: "sandbox"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres123"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"