version: "3.9"
services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_DB: "sandbox"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres123"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"
      DATABASE_NAME: "sandbox"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "postgres123"
      SERVER_HOST: ""
      SERVER_PORT: "8080"
      SERVER_WRITE_TIMEOUT: "10s"
      SERVER_READ_TIMEOUT: "10s"
      GIN_MODE: "release"
    depends_on:
      - postgres
    ports:
      - "8080:8080"
